### ISSUE TITLE
[BUG] Raid Frame fading still leaves the background visible

### ISSUE THREAD

**Issue by Arkios64** [PhenomDevel/BlizzHUDTweaks#9]
This is with 0% alpha, which means invisibility for all other frames:
![image](https://user-images.githubusercontent.com/78656397/203877178-594b983e-591d-44af-8941-59b6c7e6443c.png)

Basically, the `Raid Frame` functionally only gets darker with lower alpha instead of more transparent, because it has a dark grey background behind it.
The fading functionality itself works as expected. I've also tried disabling all other addons, just to make sure.

**Comment by PhenomDevel** [comment]
Looks fine to me ;)...

Jokes aside. I'll have a look. I just added the obvious frames for now and i might have to change this to a frame set instead of a single frame for each option since a lot of ui elements consist of many frames which - unfortunately - don't attach very well to another.

**Comment by PhenomDevel** [comment]
Should be fixed in 1.23.0-beta. This is a rather large change so any testing would be appreciated.

**Comment by Arkios64** [comment]
I'm in the process of setting up for testing and noticed a few things during that (in `1.23.0-beta`):
- The Tooltips for enabling different triggers mention the order reduntantly, since it is already noted above.
- `Instanced Area Fade` mentions `Treat target as in combat` specifically a second time, which is even more redundant.
- It would be great to be able to `Copy from` the `Global Settings` like you can from other frames, for when you only want to change one thing; currently you have to go back and forth between them and manually set every value.
- The list of frames in `Copy from` isn't ordered alphabetically like the the normal list. It also has `TotemFrameOriginalPoint` in the list and one option aboce `Action Bar 1` that only shows the bottom 3-ish pixels of the text. Wait, strike that last part, those pixels are from the `Use global options` Toggle being visible through that part of the selection box^^
- The new option for `Treat target as in combat` individually should probably start initially turned off, since otherwise absolutely everyone will have to manually disable it for every single frame they don't use the global settings on.

Since a lot of that is probably just due to different beta versions and not worth an individual issue I'll just mention it here directly. I'll give feedback for the tests once I've actually managed to find a group/raid (I didn't actually check if groups had the same issue before, since I'm rarely in a group atm).

**Comment by PhenomDevel** [comment]
> The Tooltips for enabling different triggers mention the order reduntantly, since it is already noted above.

This is on purpose since i know not a lot of people actually read the stuff that is noted there.

> Instanced Area Fade mentions Treat target as in combat specifically a second time, which is even more redundant.

This one i'll remove

> The list of frames in Copy from isn't ordered alphabetically like the the normal list. It also has TotemFrameOriginalPoint in the list and one option above Action Bar 1 that only shows the bottom 3-ish pixels of the text. Wait, strike that last part, those pixels are from the Use global options Toggle being visible through that part of the selection box^^

I'll generate the list with a different strategy. For the order i don't really know how to force AceConfig to list them Alphabetically since i already use the names as keys for the table. So i am afraid i have no fix for this.

> The new option for Treat target as in combat individually should probably start initially turned off, since otherwise absolutely everyone will have to manually disable it for every single frame they don't use the global settings on.

Yes you're right. I'll fix this.

**Comment by PhenomDevel** [comment]
Everything above added in version `1.24.2`.

**Comment by PhenomDevel** [comment]
The global frame is not present in the frame list when copying to another frame.

**Comment by PhenomDevel** [comment]
Seems fixed now

**Comment by Arkios64** [comment]
I still can't find anything I would be able to interpret as `global` in the list:
![image](https://user-images.githubusercontent.com/78656397/205859935-1b75d190-a060-4a92-8d1c-2d37b1a61b57.png)

**Comment by PhenomDevel** [comment]
Yeah because i am an idiot. I closed this due to another issue i fixed. I just thought it was this issue :D

**Comment by Arkios64** [comment]
Test was successful, great work as always!
